### ISSUE TITLE
Rename the project?

### ISSUE THREAD

**Issue by ha-warmup** [ha-warmup/warmup#1]
Before we get too far, do we want to rename this to be simply '**warmup**' instead of **warmup4IE**.

**Comment by PtolemyIV** [comment]
I agree that probably makes sense. Not sure what other smart systems they do but could theoretically be expanded to support them also in the future anyhow.

**Comment by foxy82** [comment]
It was requested to call it warmup by the Home Assistant devs - so we need to rename to warmup.

https://github.com/home-assistant/home-assistant/pull/21144#discussion_r282139739

**Comment by artmg** [comment]
This repo has now been renamed

**Comment by artmg** [comment]
I am having issues forking this repo into my account because of the fork I have from alex/foxy (even if the name has been changed). Reading up on this I'm not sure we can do much about it, so I'm tempted to rename this back and we can start a brand new fresh repo under the 'warmup' name. Please let me know if you see any issues with this approach. Thanks

**Comment by artmg** [comment]
Actually what I did was to delete my old fork from previous versions and fork afresh from here, but I don't know how others feel about doing that.
